<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\PPEManagement.Context.EntityFrameworkCore\PPEManagement.Context.EntityFrameworkCore.csproj" />
      <ProjectReference Include="..\PPEManagement.Dal.Contracts\PPEManagement.Dal.Contracts.csproj" />
      <ProjectReference Include="..\PPEManagement.Entities\PPEManagement.Entities.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.12" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    </ItemGroup>

</Project>
