<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentAssertions" Version="7.2.2" />
      <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
      <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="xunit.v3" Version="3.2.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\PPEManagement.Context.Tests\PPEManagement.Context.Tests.csproj" />
      <ProjectReference Include="..\PPEManagement.Entities\PPEManagement.Entities.csproj" />
      <ProjectReference Include="..\PPEManagement.Repositories.Contracts\PPEManagement.Repositories.Contracts.csproj" />
      <ProjectReference Include="..\PPEManagement.Repositories\PPEManagement.Repositories.csproj" />
    </ItemGroup>

</Project>
